### Configurações Globais
@baseUrl = http://127.0.0.1:3333

# ==========================================
# 1. AUTENTICAÇÃO E LOGIN
# ==========================================

### Realizar Login (Gera o Token)
# @name login
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "",
  "password": ""
}

### Armazenar o Token do Login acima
@authToken = {{login.response.body.token}}

# ==========================================
# 2. USUÁRIOS (Rotas de Gerenciamento)
# ==========================================

### Criar Novo Usuário (Público)
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Teste",
  "email": "teste@exemplo.com",
  "password": "senha_segura_123"
}

### Listar Todos os Usuários (ADMIN)
GET {{baseUrl}}/admin/allusers
Authorization: Bearer {{authToken}}

### Atualizar Próprio Perfil (Logado)
PUT {{baseUrl}}/me
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Hevellyn Meiriane (Editado)"
}

### Listar Próprio Perfil com Tarefas
GET {{baseUrl}}/profile
Authorization: Bearer {{authToken}}

# ==========================================
# 3. ÁREA ADMINISTRATIVA (Apenas ADMIN)
# ==========================================

### Editar qualquer usuário (Apenas ADMIN)
PUT {{baseUrl}}/admin/users/a4bc44af-266d-4b96-8fd9-efad82e86a43
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "role": "USER"
}

### Deletar Usuário (Soft Delete - Apenas ADMIN)
DELETE {{baseUrl}}/admin/users/a4bc44af-266d-4b96-8fd9-efad82e86a43
Authorization: Bearer {{authToken}}

# ==========================================
# 4. TAREFAS (TASKS)
# ==========================================

### Listar Minhas Tarefas
GET {{baseUrl}}/tasks
Authorization: Bearer {{authToken}}

### Listar Todas as Tarefas (ADMIN)
GET {{baseUrl}}/admin/tasks
Authorization: Bearer {{authToken}}

### Criar Nova Tarefa
POST {{baseUrl}}/tasks
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Estudar Programação",
  "description": "Revisar conceitos de JavaScript e TypeScript",
  "status": "PENDING"
}

### Atualizar Tarefa Existente
PUT {{baseUrl}}/tasks/68e8941d-c8a3-49b7-ac58-ded9e6dd58ae
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "description": "Revisar conceitos de JavaScript e TypeScript e fazer exercícios"
}

### Deletar Tarefa
DELETE {{baseUrl}}/tasks/68e8941d-c8a3-49b7-ac58-ded9e6dd58ae
Authorization: Bearer {{authToken}}

### Obter Detalhes de uma Tarefa
GET {{baseUrl}}/tasks/5b25c108-4cab-49c9-b31c-5686e797f7e8
Authorization: Bearer {{authToken}}
# ==========================================
