### Configurações Globais
@baseUrl = http://127.0.0.1:3333

# ==========================================
# 1. AUTENTICAÇÃO E LOGIN
# ==========================================

### Realizar Login (Gera o Token)
# @name login
POST {{baseUrl}}/login
Content-Type: application/json

{
  "email": "aelin@exemplo.com",
  "password": "senha_segura_123"
}

### Armazenar o Token do Login acima
@authToken = {{login.response.body.token}}

# ==========================================
# 2. USUÁRIOS (Rotas de Gerenciamento)
# ==========================================

### Criar Novo Usuário (Público)
POST {{baseUrl}}/users
Content-Type: application/json

{
  "name": "Momo",
  "email": "momo@exemplo.com",
  "password": "senha_segura_123"
}

### Listar Todos os Usuários (ADMIN ou MANAGER)
GET {{baseUrl}}/allusers
Authorization: Bearer {{authToken}}

### Atualizar Próprio Perfil (Logado)
PUT {{baseUrl}}/users/a254e919-3318-416b-b15c-f8927d6d27b0
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "name": "Hevellyn Meiriane (Editado)"
}

# ==========================================
# 3. ÁREA ADMINISTRATIVA (Apenas ADMIN)
# ==========================================

### Promover Usuário (Apenas ADMIN)
# Essa é a rota do seu novo AdminController
PUT {{baseUrl}}/admin/users/e2708171-5812-48cd-9822-1d72deb17320/role
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "role": "ADMIN"
}

### Deletar Usuário (Soft Delete - Apenas ADMIN)
DELETE {{baseUrl}}/users/100d064a-0c39-4bd6-8d71-18d84b326a51
Authorization: Bearer {{authToken}}

# ==========================================
# 4. TAREFAS (TASKS)
# ==========================================

### Listar Minhas Tarefas
GET {{baseUrl}}/tasks
Authorization: Bearer {{authToken}}

### Listar Todas as Tarefas (ADMIN)
GET {{baseUrl}}/admin/tasks
Authorization: Bearer {{authToken}}

### Criar Nova Tarefa
POST {{baseUrl}}/tasks
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Estudar Eletromagnetismo",
  "description": "Revisar equações de Maxwell"
}

### Atualizar Tarefa Existente
PUT {{baseUrl}}/tasks/8a52dc68-3e7f-4464-82b3-a5eb96ad4ed8
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "userId": "4ea3ed94-618c-47ba-a593-8e892a5b6c56"
}